version: '2'
services:
    db:
        image: mariadb
        ports:
            - "3308:3306"
        volumes:
           - ./db:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel

    web:
        build: ./apache2
#        image: php:7.2.2-apache
        links:
            - db
        volumes:
            - ./apache2/sites-enabled/:/etc/apache2/sites-enabled
            - ./laravel:/var/www/html/
            - /home/ivanatora/weather_data:/weather_data
        ports:
            - 8004:80
        stdin_open: true
        tty: true
#    php:
#        build: ./php-fpm
#        expose:
#            - "9000"
#        tty: true
#        volumes:
#            - ./laravel:/var/www/laravel
#            - /home/ivanatora/weather_data:/weather_data
#        links:
#            - db

#    apache:
#        image: smtripat/apache-php-fpm:latest
#        ports:
#          - 8004:80
#        volumes:
#          - ./laravel:/var/www/html/docroot
#          - ./apache2/logs/:/var/log/apache2
#          - ./apache2/sites-enabled/:/etc/apache2/sites-enabled

#    nginx:
#        build: ./nginx
#        ports:
#            - "8002:80"
#        links:
#            - php
#        volumes_from:
#            - php
#        volumes:
#            - ./logs/nginx/:/var/log/nginx
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8182:80
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            PMA_HOST: db
        depends_on:
            - db
#    cron:
#        build: ./cron
#        volumes_from:
#            - php
